void recruitEmployee (struct employee ** headLL) {

    int numDependents=0;

    //manually enter the employee data from standard input
    //the user enters the fname, lname of the employee
    scanf("%s", &fname);
    scanf("%s", &lname);

    //note that empId is unique for every employee and is automatically generated by the program
    //scanf("%d", &empId);

    //prompt user to enter the dependent names one by one
    for (while continue == 'y') {

        scanf("%s", dependent[i]);
        numDependents++;

    } //end for

    //add their information to the end of the linked list passed as a parameter to this function
    //nextEmployee=determine somehow

} //end recruitEmployees
